name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Roda todos os dias à meia-noite UTC

  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg

      - name: Commit e push da animação
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add dist/github-snake.svg
          git commit -m "Atualizando animação da cobrinha" || echo "Nenhuma mudança"
          git push
